name = "url-shortener-pages"
type = "javascript"

[build]
command   = ""
publish   = "."
functions = "functions"

# KV namespace bindings
[[kv_namespaces]]
binding = "LINKS"
id      = "a2774cd1a1374de49b12c0d62e255fcd"

[[kv_namespaces]]
binding = "LOGS"
id      = "de01551a3b504205b5712da796f010fd"

[[kv_namespaces]]
binding = "STATS"
id      = "bed69b5520cc4c4294d128840a097974"

[[kv_namespaces]]
binding = "STATS_DAY"
id      = "3bf49d57aa3b4f9fba680056a26bd6f5"

[[kv_namespaces]]
binding = "GEO"
id      = "2a629d3120dc498fae067825c640343f"

# você pode também adicionar via `wrangler secret put ADMIN_TOKEN`
[vars]
ADMIN_TOKEN = "SECRET"


2a629d3120dc498fae067825c640343f
