name: add-short-link
on:
  repository_dispatch:
    types: [new_link]

permissions:
  contents: write

jobs:
  append:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Add link to links.json
        env:
          CODE: ${{ github.event.client_payload.code }}
          URL:  ${{ github.event.client_payload.url }}
        run: |
          FILE=links.json
          if [ ! -f "$FILE" ]; then echo "{}" > $FILE; fi
          jq --arg k "$CODE" --arg v "$URL" '.[$k]=$v' $FILE > tmp && mv tmp $FILE

      - name: Commit & push
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "add short link: ${{ env.CODE }}"
